version: "3"

networks: 
    shopnetwork:
        driver: bridge

services:
    db:
        image: postgres:12.4-alpine
        container_name: shop.db
        ports: 
            - 5432:5432
        networks: 
            - shopnetwork
        environment:
            POSTGRES_PASSWORD: root     

    api:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: shop.api
        ports: 
            - 3000:3000
        networks: 
            - shopnetwork
        command: yarn start:prod
        depends_on: 
            - db
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: root
            DB: postgres
            JWT_SECRET: hardsecret
            JWT_EXPIRES_IN: 24h